import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Theme = "light" | "dark";
export type Lang = "en" | "ur" | "ru";

type Dict = Record<string, string>;

const en: Dict = {
  // nav
  "nav.home": "Home",
  "nav.discover": "Discover",
  "nav.matches": "Matches",
  "nav.chats": "Chats",
  "nav.profile": "Profile",
  // common
  "common.back": "Back",
  "common.continue": "Continue",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.save": "Save",
  "common.search": "Search",
  "common.filter": "Filters",
  "common.viewAll": "See all",
  "common.retry": "Retry",
  "common.loading": "Loading…",
  "common.empty": "Nothing here yet",
  "common.error": "Something went wrong",
  "common.online": "Online",
  "common.typing": "typing…",
  "common.today": "Today",
  "common.yesterday": "Yesterday",
  "common.earlier": "Earlier",
  "common.unread": "Unread",
  "common.read": "Read",
  "common.yrs": "yrs",
  "common.edit": "Edit",
  "common.view": "View",
  "common.approve": "Approve",
  "common.reject": "Reject",
  "common.decline": "Decline",
  "common.investigate": "Investigate",
  "common.suspend": "Suspend",
  "common.dismiss": "Dismiss",
  "common.pending": "Pending",
  "common.verified": "Verified",
  "common.step": "Step",
  "common.of": "of",
  "common.optional": "Optional",
  "common.required": "Required",
  "common.yes": "Yes",
  "common.no": "No",
  "common.other": "Other",
  // splash
  "splash.tagline":
    '"And of His signs is that He created for you from yourselves mates…" — Ar-Rum 30:21',
  "splash.skip": "Skip",
  // welcome
  "welcome.title": "A meeting written before the world began.",
  "welcome.subtitle":
    "Misaq is a covenant — a matrimonial platform built on Islamic values, dignity, and family involvement.",
  "welcome.create": "Create account",
  "welcome.have": "I already have an account",
  "welcome.pillar1.t": "Verified profiles",
  "welcome.pillar1.d": "Every member is verified with CNIC and a Wali interview.",
  "welcome.pillar2.t": "Family at the centre",
  "welcome.pillar2.d": "Your Wali sees every conversation. Nothing hidden.",
  "welcome.pillar3.t": "Nikah, not dating",
  "welcome.pillar3.d": "Structured proposals — no swiping, no ambiguity.",
  // theme onboarding
  "theme.step": "Step 1 of 2",
  "theme.title": "Choose your ambience",
  "theme.hint":
    "Set the tone that feels most tranquil to you. You can change it any time from Settings.",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "theme.lightDesc": "Cream & maroon. Bright and airy.",
  "theme.darkDesc": "Deep maroon on black. Serene and quiet.",
  // language
  "lang.step": "Step 2 of 2",
  "lang.title": "Choose your language",
  "lang.hint": "You may switch anytime from Settings.",
  "lang.continue": "Continue",
  // auth login
  "auth.login.title": "Welcome back",
  "auth.login.subtitle": "Sign in to continue your search with barakah.",
  "auth.login.email": "Email or phone",
  "auth.login.emailPh": "you@example.com",
  "auth.login.password": "Password",
  "auth.login.passwordPh": "••••••••",
  "auth.login.remember": "Remember me",
  "auth.login.forgot": "Forgot?",
  "auth.login.signin": "Sign in",
  "auth.login.or": "or",
  "auth.login.wali": "Sign in as Wali / Guardian",
  "auth.login.new": "New here?",
  "auth.login.create": "Create an account",
  "auth.login.admin": "Administrator login",
  "auth.login.error": "Invalid email or password.",
  // register chooser
  "auth.reg.title": "Create account",
  "auth.reg.hint": "Choose who is registering.",
  "auth.reg.member.t": "Bride or Groom",
  "auth.reg.member.d":
    "Create your profile, receive proposals, and involve your family through your Wali.",
  "auth.reg.wali.t": "Wali / Guardian",
  "auth.reg.wali.d":
    "Register to oversee a linked member — view proposals, monitor chats, and safeguard the process.",
  "auth.reg.adminNote":
    "Administrators are pre-created. Public admin registration is not available on Misaq.",
  "auth.reg.already": "Already registered?",
  "auth.reg.signin": "Sign in",
  // registration wizard
  "reg.back": "Back",
  "reg.continue": "Continue",
  "reg.finish": "Finish & enter Misaq",
  "reg.step": "Step",
  "reg.of": "of",
  "reg.title.member": "Member Registration",
  "reg.title.wali": "Wali Registration",
  "reg.s.personal": "Personal",
  "reg.s.education": "Education",
  "reg.s.religious": "Religious",
  "reg.s.dowry": "Dowry",
  "reg.s.family": "Family",
  "reg.s.wali": "Wali",
  "reg.s.aboutYou": "About You",
  "reg.s.relationship": "Relationship",
  "reg.s.verification": "Verification",
  "reg.sec.personal": "Personal information",
  "reg.sec.personalHint": "Only shown to matched families.",
  "reg.sec.eduProf": "Education & profession",
  "reg.sec.religious": "Religious information",
  "reg.sec.religiousHint": "Predefined options only — helps families find the right match.",
  "reg.sec.dowry": "Dowry preference",
  "reg.sec.dowryHint": "Answered honestly — barakah in transparency.",
  "reg.sec.family": "Family information",
  "reg.sec.waliInfo": "Wali information",
  "reg.sec.waliInfoHint":
    "Every Member on Misaq must link one Wali. This person will oversee your journey.",
  "reg.sec.aboutYou": "About you",
  "reg.sec.linkedMember": "Linked member",
  "reg.sec.linkedMemberHint": "Enter the details of the bride or groom you will oversee.",
  "reg.sec.verify": "Verification",
  "reg.sec.verifyHint": "Your identity keeps every member safe.",
  "reg.l.fullName": "Full name",
  "reg.l.dob": "Date of birth",
  "reg.l.height": "Height",
  "reg.l.gender": "Gender",
  "reg.l.country": "Country",
  "reg.l.city": "City",
  "reg.l.nationality": "Nationality",
  "reg.l.education": "Education",
  "reg.l.profession": "Profession",
  "reg.l.income": "Monthly income",
  "reg.l.prayer": "Prayer level",
  "reg.l.quran": "Quran reading",
  "reg.l.knowledge": "Islamic knowledge",
  "reg.l.beard": "Beard",
  "reg.l.hijab": "Hijab",
  "reg.l.dress": "Islamic dress",
  "reg.l.environment": "Religious environment",
  "reg.l.goals": "Islamic goals",
  "reg.l.forGroom": "For Groom",
  "reg.l.forBride": "For Bride",
  "reg.l.fatherAlive": "Father alive",
  "reg.l.motherAlive": "Mother alive",
  "reg.l.familyType": "Family type",
  "reg.l.brothers": "Brothers",
  "reg.l.sisters": "Sisters",
  "reg.l.waliName": "Wali name",
  "reg.l.rel": "Relationship",
  "reg.l.phone": "Phone",
  "reg.l.whatsapp": "WhatsApp",
  "reg.l.email": "Email",
  "reg.l.cnic": "CNIC number",
  "reg.l.memberName": "Member's full name",
  "reg.l.memberId": "Member's Misaq ID or phone",
  "reg.ph.name": "e.g. Ahmed Raza",
  "reg.ph.dob": "DD / MM / YYYY",
  "reg.ph.height": "5' 10\"",
  "reg.ph.country": "Pakistan",
  "reg.ph.city": "Lahore",
  "reg.ph.zero": "0",
  "reg.ph.phone": "+92 300 0000000",
  "reg.ph.emailWali": "wali@example.com",
  "reg.ph.cnic": "XXXXX-XXXXXXX-X",
  "reg.upload.cnicFront": "CNIC Front",
  "reg.upload.cnicBack": "CNIC Back",
  "reg.upload.selfie": "Selfie",
  "reg.upload.tap": "Tap to upload",
  "reg.dowry.needGender":
    "Please select your gender on the Personal step to see the right options.",
  // option chips
  "reg.o.male": "Male",
  "reg.o.female": "Female",
  "reg.o.nat.pk": "Pakistani",
  "reg.o.nat.in": "Indian",
  "reg.o.nat.uk": "British",
  "reg.o.nat.us": "American",
  "reg.o.nat.ae": "Emirati",
  "reg.o.nat.other": "Other",
  "reg.o.ed.matric": "Matric",
  "reg.o.ed.inter": "Intermediate",
  "reg.o.ed.diploma": "Diploma",
  "reg.o.ed.bach": "Bachelor's",
  "reg.o.ed.mast": "Master's",
  "reg.o.ed.mphil": "MPhil",
  "reg.o.ed.phd": "PhD",
  "reg.o.pr.student": "Student",
  "reg.o.pr.teacher": "Teacher",
  "reg.o.pr.doctor": "Doctor",
  "reg.o.pr.engineer": "Engineer",
  "reg.o.pr.business": "Business",
  "reg.o.pr.govt": "Government",
  "reg.o.pr.private": "Private",
  "reg.o.pr.freelance": "Freelancer",
  "reg.o.inc.a": "Under 50k",
  "reg.o.inc.b": "50k – 100k",
  "reg.o.inc.c": "100k – 250k",
  "reg.o.inc.d": "250k – 500k",
  "reg.o.inc.e": "500k+",
  "reg.o.pray.never": "Never",
  "reg.o.pray.some": "Sometimes",
  "reg.o.pray.friday": "Friday Only",
  "reg.o.pray.daily": "Daily",
  "reg.o.pray.five": "Five Times",
  "reg.o.pray.fiveM": "Five Times in Mosque",
  "reg.o.q.no": "Cannot Read",
  "reg.o.q.learn": "Learning",
  "reg.o.q.some": "Sometimes",
  "reg.o.q.daily": "Daily",
  "reg.o.q.hafiz": "Hafiz",
  "reg.o.k.beg": "Beginner",
  "reg.o.k.int": "Intermediate",
  "reg.o.k.good": "Good",
  "reg.o.k.adv": "Advanced",
  "reg.o.k.scholar": "Scholar",
  "reg.o.b.no": "No",
  "reg.o.b.short": "Short Beard",
  "reg.o.b.sunnah": "Sunnah Beard",
  "reg.o.h.no": "No",
  "reg.o.h.some": "Sometimes",
  "reg.o.h.reg": "Regular",
  "reg.o.h.niqab": "Niqab",
  "reg.o.dr.modern": "Modern",
  "reg.o.dr.modest": "Modest",
  "reg.o.dr.trad": "Traditional",
  "reg.o.dr.sunnah": "Sunnah",
  "reg.o.env.normal": "Normal",
  "reg.o.env.rel": "Religious",
  "reg.o.env.high": "Highly Religious",
  "reg.o.g.hajj": "Hajj",
  "reg.o.g.umrah": "Umrah",
  "reg.o.g.hifz": "Memorize Quran",
  "reg.o.g.ed": "Islamic Education",
  "reg.o.g.family": "Raise Religious Family",
  "reg.o.dw.mAccept": "I Accept Dowry",
  "reg.o.dw.mNo": "I Do Not Accept Dowry",
  "reg.o.dw.mDont": "Doesn't Matter",
  "reg.o.dw.fGive": "We Will Give Dowry",
  "reg.o.dw.fNo": "We Will Not Give Dowry",
  "reg.o.dw.fPref": "Prefer Not to Answer",
  "reg.o.ft.joint": "Joint Family",
  "reg.o.ft.sep": "Separate Family",
  "reg.o.rel.father": "Father",
  "reg.o.rel.mother": "Mother",
  "reg.o.rel.brother": "Brother",
  "reg.o.rel.sister": "Sister",
  "reg.o.rel.uncle": "Uncle",
  "reg.o.rel.aunt": "Aunt",
  "reg.o.rel.guardian": "Guardian",
  // home
  "home.greeting": "Assalamu alaikum",
  "home.newMatches": "New matches",
  "home.proposals": "Proposals",
  "home.chats": "Chats",
  "home.featured": "Featured matches",
  "home.recent": "Recent proposals",
  "home.proposalReceived": "Proposal received",
  // discover
  "discover.title": "Discover",
  "discover.count": "verified profiles matching your filters",
  "discover.filter.all": "All",
  // matches
  "matches.title": "Matches & proposals",
  "matches.received": "Received",
  "matches.sent": "Sent",
  "matches.accepted": "Accepted",
  "matches.view": "View",
  "matches.accept": "Accept",
  "matches.decline": "Decline",
  "matches.openChat": "Open chat",
  "matches.empty": "No proposals in this section yet.",
  // chats
  "chats.title": "Chats",
  "chats.waliNotice": "Your Wali sees every conversation.",
  "chats.empty": "No conversations yet. Send a proposal to begin.",
  "chats.voice": "Voice",
  "chats.messagePlaceholder": "Message with adab…",
  "chats.online": "Online • Wali is watching",
  "chats.consent": "This conversation is visible to your Wali. Speak with adab.",
  "chats.startOfDay": "Today",
  // profile
  "profile.about": "About",
  "profile.eduProf": "Education & profession",
  "profile.religion": "Religious information",
  "profile.family": "Family",
  "profile.wali": "Wali information",
  "profile.dowry": "Dowry preference",
  "profile.compat": "Compatible profiles",
  "profile.education": "Education",
  "profile.profession": "Profession",
  "profile.height": "Height",
  "profile.sect": "Sect",
  "profile.prayer": "Prayer",
  "profile.quran": "Quran",
  "profile.hijab": "Hijab",
  "profile.beard": "Beard",
  "profile.father": "Father",
  "profile.mother": "Mother",
  "profile.siblings": "Siblings",
  "profile.familyType": "Family type",
  "profile.waliName": "Wali",
  "profile.verified": "Verified",
  "profile.sendProposal": "Send proposal",
  "profile.save": "Save",
  "profile.myTitle": "Your profile",
  "profile.mashAllah": "Ma sha Allah",
  "profile.views": "Profile views",
  "profile.complete": "Complete",
  "profile.upgrade": "Upgrade to Platinum",
  "profile.upgradeDesc": "Unlimited proposals · priority visibility",
  "profile.edit": "Edit profile",
  "profile.editDesc": "Personal, religious, family, dowry",
  "profile.viewed": "Who viewed me",
  "profile.viewedDesc": "42 members this week",
  "profile.myWali": "My Wali",
  "profile.myWaliDesc": "Abdullah Rahman · Father · Verified",
  "profile.strength": "Profile strength",
  "profile.strengthPersonal": "Personal information",
  "profile.strengthReligious": "Religious information",
  "profile.strengthFamily": "Family details",
  "profile.strengthPhotos": "Photos",
  // notifications
  "notif.title": "Notifications",
  "notif.markAllRead": "Mark all read",
  "notif.empty": "You're all caught up.",
  // premium
  "premium.eyebrow": "Misaq Premium",
  "premium.title": "Invest in a purposeful search.",
  "premium.subtitle":
    "Members with Premium receive up to 4× more sincere proposals — with families involved from the first hello.",
  "premium.mostChosen": "Most chosen",
  "premium.choose": "Choose",
  "premium.footer": "All plans are halal-compliant subscriptions. Cancel anytime.",
  // settings
  "settings.title": "Settings",
  "settings.theme": "Theme",
  "settings.language": "Language",
  "settings.account": "Account",
  "settings.preferences": "Preferences",
  "settings.support": "Support",
  "settings.logout": "Log out",
  "settings.myAccount": "My account",
  "settings.privacy": "Privacy",
  "settings.security": "Security & 2FA",
  "settings.notifications": "Notifications",
  "settings.premium": "Misaq Premium",
  "settings.help": "Help centre",
  "settings.about": "About Misaq",
  "settings.terms": "Terms of service",
  "settings.policy": "Privacy policy",
  // calls
  "call.voice": "Voice call",
  "call.video": "Video call",
  "call.calling": "Calling…",
  "call.connecting": "Connecting securely",
  "call.mute": "Mute",
  "call.end": "End",
  "call.speaker": "Speaker",
  "call.camera": "Camera",
  "call.flip": "Flip",
  // wali
  "wali.dashboard": "Wali Dashboard",
  "wali.name": "Abdullah Rahman",
  "wali.guardianOf": "You are guardian of",
  "wali.stats.proposals": "Proposals",
  "wali.stats.chats": "Chats",
  "wali.stats.flags": "Flags",
  "wali.current": "Current proposals",
  "wali.viewAll": "View all",
  "wali.inProgress": "Chats in progress",
  "wali.monitor": "Monitor",
  "wali.fullVis": "You have full visibility.",
  "wali.fullVisDesc":
    "Every message, voice note, and call between your ward and other members is available for you to review.",
  "wali.proposals.title": "Proposals",
  "wali.proposals.for": "For",
  "wali.reviewProfile": "Review profile",
  "wali.waliChat": "Wali-to-Wali chat",
  "wali.chats.title": "Chat monitoring",
  "wali.chats.for": "conversations",
  "wali.chats.viewChat": "View chat",
  "wali.chats.viewProfile": "View profile",
  "wali.chats.block": "Block",
  "wali.chats.delete": "Delete",
  "wali.chats.report": "Report",
  "wali.thread.readOnly": "Read-only oversight",
  "wali.thread.notice": "You are viewing this conversation as Wali. Members are aware.",
  "wali.review.subtitle":
    "Reviewing this profile as Wali. Contact their Wali directly through the linked details below.",
  "wali.review.theirWali": "Their Wali",
  "wali.review.waliName": "Ismail Rahman (Father)",
  "wali.review.waliContact": "+92 300 ••• ••• · Verified with CNIC",
  "wali.review.message": "Message Wali directly",
  "wali.review.religious": "Religious",
  "wali.settings.title": "Wali settings",
  "wali.set.profile": "Profile & verification",
  "wali.set.privacy": "Ward's privacy controls",
  "wali.set.notif": "Notifications",
  "wali.set.lang": "Language",
  "wali.set.theme": "Theme",
  // admin
  "admin.header": "Misaq Admin",
  "admin.restricted": "Restricted console",
  "admin.super": "SUPER",
  "admin.nav.dashboard": "Dashboard",
  "admin.nav.members": "Members",
  "admin.nav.walis": "Walis",
  "admin.nav.verify": "Verify",
  "admin.nav.reports": "Reports",
  "admin.nav.chats": "Chats",
  "admin.nav.calls": "Calls",
  "admin.nav.payments": "Payments",
  "admin.nav.plans": "Plans",
  "admin.nav.analytics": "Analytics",
  "admin.nav.admins": "Admins",
  "admin.nav.cms": "CMS",
  "admin.nav.settings": "Settings",
  "admin.kpi.members": "Total members",
  "admin.kpi.walis": "Active Walis",
  "admin.kpi.chats": "Live chats",
  "admin.kpi.mrr": "MRR",
  "admin.kpi.thisWeek": "this week",
  "admin.kpi.flagged": "flagged",
  "admin.nikahs": "Nikahs celebrated",
  "admin.mom": "MoM",
  "admin.attention": "Requires attention",
  "admin.att.verif": "Pending verifications",
  "admin.att.chats": "Flagged chats",
  "admin.att.reports": "User reports",
  "admin.att.disputes": "Payment disputes",
  "admin.signups": "Latest signups",
  "admin.members.search": "Search members…",
  "admin.members.f.all": "All",
  "admin.members.f.verified": "Verified",
  "admin.members.f.pending": "Pending",
  "admin.members.f.premium": "Premium",
  "admin.members.f.reported": "Reported",
  "admin.members.f.suspended": "Suspended",
  "admin.walis.title": "Walis",
  "admin.walis.of": "Wali of",
  "admin.verify.pending": "pending verifications",
  "admin.verify.submitted": "Submitted 2h ago · CNIC · Selfie",
  "admin.reports.reasons.msg": "Inappropriate message",
  "admin.reports.reasons.fake": "Fake profile",
  "admin.reports.reasons.harass": "Harassment",
  "admin.reports.reasons.spam": "Spam / marketing",
  "admin.reports.by": "By",
  "admin.reports.against": "Against",
  "admin.chats.summary": "active conversations",
  "admin.chats.flagged": "flagged",
  "admin.chats.msgs": "messages",
  "admin.chats.last": "Last",
  "admin.calls.waliPresent": "Wali present",
  "admin.calls.noWali": "No Wali",
  "admin.pay.today": "Today",
  "admin.pay.month": "This month",
  "admin.pay.refunds": "Refunds",
  "admin.pay.status.success": "Success",
  "admin.pay.status.refund": "Refund",
  "admin.pay.status.failed": "Failed",
  "admin.plans.subs": "subscribers",
  "admin.plans.month": "month",
  "admin.analytics.dau": "DAU",
  "admin.analytics.retention": "Retention D30",
  "admin.analytics.avg": "Avg. proposals / user",
  "admin.analytics.mtn": "Match-to-nikah",
  "admin.analytics.byCountry": "Members by country",
  "admin.cms.terms": "Terms of service",
  "admin.cms.privacy": "Privacy policy",
  "admin.cms.community": "Community guidelines",
  "admin.cms.qa": "Islamic Q&A",
  "admin.cms.help": "Help centre",
  "admin.cms.banners": "Homepage banners",
  "admin.cms.updated": "Updated",
  "admin.cms.articles": "articles",
  "admin.cms.active": "active",
  "admin.admins.invite": "Invite admin",
  "admin.admins.roles.super": "Super Admin",
  "admin.admins.roles.mod": "Moderator",
  "admin.admins.roles.support": "Support",
  "admin.set.platform": "Platform",
  "admin.set.security": "Security",
  "admin.set.compliance": "Compliance",
  "admin.set.p.branding": "Branding & logo",
  "admin.set.p.onboarding": "Onboarding flow",
  "admin.set.p.algo": "Compatibility algorithm",
  "admin.set.p.langs": "Language packs",
  "admin.set.s.pw": "Password policy",
  "admin.set.s.2fa": "Two-factor for admins",
  "admin.set.s.sess": "Session limits",
  "admin.set.s.audit": "Audit log",
  "admin.set.c.retention": "Data retention",
  "admin.set.c.forgotten": "Right to be forgotten",
  "admin.set.c.export": "Export data",
  "admin.set.c.laws": "Regional laws",
  "admin.login.title": "Administrator",
  "admin.login.subtitle": "Restricted access",
  "admin.login.notice": "Admin accounts are pre-created. No public registration.",
  "admin.login.email": "Admin email",
  "admin.login.emailPh": "admin@misaq.app",
  "admin.login.pw": "Password",
  "admin.login.pwPh": "••••••••",
  "admin.login.otp": "Two-factor code",
  "admin.login.otpPh": "6-digit code",
  "admin.login.enter": "Enter admin console",
  "admin.login.back": "Back to member login",
  // empty / errors
  "state.empty": "Nothing here yet.",
  "state.error.title": "Something went wrong",
  "state.error.desc": "Please try again in a moment.",
};

const ur: Dict = {
  "nav.home": "ہوم",
  "nav.discover": "تلاش",
  "nav.matches": "میچز",
  "nav.chats": "چیٹس",
  "nav.profile": "پروفائل",
  "common.back": "واپس",
  "common.continue": "جاری رکھیں",
  "common.cancel": "منسوخ",
  "common.confirm": "تصدیق",
  "common.save": "محفوظ",
  "common.search": "تلاش",
  "common.filter": "فلٹرز",
  "common.viewAll": "سب دیکھیں",
  "common.retry": "دوبارہ کوشش",
  "common.loading": "لوڈ ہو رہا ہے…",
  "common.empty": "ابھی کچھ نہیں",
  "common.error": "کچھ غلط ہو گیا",
  "common.online": "آن لائن",
  "common.typing": "لکھ رہے ہیں…",
  "common.today": "آج",
  "common.yesterday": "کل",
  "common.earlier": "پہلے",
  "common.unread": "غیر پڑھی",
  "common.read": "پڑھی گئی",
  "common.yrs": "سال",
  "common.edit": "ترمیم",
  "common.view": "دیکھیں",
  "common.approve": "منظور",
  "common.reject": "مسترد",
  "common.decline": "رد",
  "common.investigate": "تحقیق",
  "common.suspend": "معطل",
  "common.dismiss": "برخاست",
  "common.pending": "زیر التوا",
  "common.verified": "تصدیق شدہ",
  "common.step": "مرحلہ",
  "common.of": "از",
  "common.optional": "اختیاری",
  "common.required": "لازمی",
  "common.yes": "ہاں",
  "common.no": "نہیں",
  "common.other": "دیگر",
  "splash.tagline":
    '"اور اس کی نشانیوں میں سے یہ ہے کہ اس نے تمہارے لیے تمہاری جنس سے جوڑے بنائے…" — الروم 30:21',
  "splash.skip": "چھوڑیں",
  "welcome.title": "ایک ملاقات جو دنیا سے پہلے لکھی جا چکی۔",
  "welcome.subtitle":
    "میثاق ایک عہد ہے — ایک نکاح پلیٹ فارم جو اسلامی اقدار، وقار اور خاندانی شمولیت پر قائم ہے۔",
  "welcome.create": "اکاؤنٹ بنائیں",
  "welcome.have": "میرا پہلے سے اکاؤنٹ ہے",
  "welcome.pillar1.t": "تصدیق شدہ پروفائلز",
  "welcome.pillar1.d": "ہر رکن CNIC اور ولی انٹرویو سے تصدیق شدہ ہے۔",
  "welcome.pillar2.t": "خاندان مرکز میں",
  "welcome.pillar2.d": "آپ کا ولی ہر گفتگو دیکھتا ہے۔ کچھ پوشیدہ نہیں۔",
  "welcome.pillar3.t": "نکاح، نہ ڈیٹنگ",
  "welcome.pillar3.d": "منظم پیغام — نہ swipe، نہ ابہام۔",
  "theme.step": "مرحلہ 1 از 2",
  "theme.title": "اپنی فضا چنیں",
  "theme.hint": "وہ رنگ چنیں جو آپ کے دل کو سکون دے۔ آپ سیٹنگز سے بدل سکتے ہیں۔",
  "theme.light": "روشن",
  "theme.dark": "گہری",
  "theme.lightDesc": "کریم اور مروون۔ روشن اور کشادہ۔",
  "theme.darkDesc": "کالے پر گہرا مروون۔ پرسکون اور خاموش۔",
  "lang.step": "مرحلہ 2 از 2",
  "lang.title": "اپنی زبان چنیں",
  "lang.hint": "آپ کسی بھی وقت سیٹنگز سے تبدیل کر سکتے ہیں۔",
  "lang.continue": "جاری رکھیں",
  "auth.login.title": "خوش آمدید",
  "auth.login.subtitle": "برکت کے ساتھ اپنی تلاش جاری رکھنے کے لیے سائن ان کریں۔",
  "auth.login.email": "ای میل یا فون",
  "auth.login.emailPh": "you@example.com",
  "auth.login.password": "پاس ورڈ",
  "auth.login.passwordPh": "••••••••",
  "auth.login.remember": "مجھے یاد رکھیں",
  "auth.login.forgot": "بھول گئے؟",
  "auth.login.signin": "سائن ان",
  "auth.login.or": "یا",
  "auth.login.wali": "ولی/سرپرست کے طور پر سائن ان",
  "auth.login.new": "نئے ہیں؟",
  "auth.login.create": "اکاؤنٹ بنائیں",
  "auth.login.admin": "منتظم لاگ ان",
  "auth.login.error": "غلط ای میل یا پاس ورڈ۔",
  "auth.reg.title": "اکاؤنٹ بنائیں",
  "auth.reg.hint": "کون رجسٹر ہو رہا ہے؟",
  "auth.reg.member.t": "دلہن یا دولہا",
  "auth.reg.member.d": "پروفائل بنائیں، پیغام وصول کریں اور اپنے ولی کے ذریعے خاندان کو شامل کریں۔",
  "auth.reg.wali.t": "ولی / سرپرست",
  "auth.reg.wali.d": "کسی رکن کی نگرانی کے لیے رجسٹر ہوں — پیغام دیکھیں، چیٹ کی نگرانی کریں۔",
  "auth.reg.adminNote": "منتظمین پہلے سے بنائے گئے ہیں۔ عوامی ایڈمن رجسٹریشن دستیاب نہیں۔",
  "auth.reg.already": "پہلے سے رجسٹرڈ ہیں؟",
  "auth.reg.signin": "سائن ان",
  "reg.back": "واپس",
  "reg.continue": "جاری رکھیں",
  "reg.finish": "مکمل کریں اور میثاق میں داخل ہوں",
  "reg.step": "مرحلہ",
  "reg.of": "از",
  "reg.title.member": "رکن رجسٹریشن",
  "reg.title.wali": "ولی رجسٹریشن",
  "reg.s.personal": "ذاتی",
  "reg.s.education": "تعلیم",
  "reg.s.religious": "دینی",
  "reg.s.dowry": "جہیز",
  "reg.s.family": "خاندان",
  "reg.s.wali": "ولی",
  "reg.s.aboutYou": "آپ کے بارے میں",
  "reg.s.relationship": "رشتہ",
  "reg.s.verification": "تصدیق",
  "reg.sec.personal": "ذاتی معلومات",
  "reg.sec.personalHint": "صرف میچ شدہ خاندانوں کو دکھایا جاتا ہے۔",
  "reg.sec.eduProf": "تعلیم اور پیشہ",
  "reg.sec.religious": "دینی معلومات",
  "reg.sec.religiousHint": "پہلے سے دی گئی اختیارات — صحیح میچ تلاش میں مدد۔",
  "reg.sec.dowry": "جہیز کی ترجیح",
  "reg.sec.dowryHint": "ایمانداری سے جواب — شفافیت میں برکت۔",
  "reg.sec.family": "خاندانی معلومات",
  "reg.sec.waliInfo": "ولی کی معلومات",
  "reg.sec.waliInfoHint": "ہر رکن کو ایک ولی منسلک کرنا لازم ہے۔",
  "reg.sec.aboutYou": "آپ کے بارے میں",
  "reg.sec.linkedMember": "منسلک رکن",
  "reg.sec.linkedMemberHint": "جس دلہن/دولہا کی آپ نگرانی کریں گے اس کی تفصیلات۔",
  "reg.sec.verify": "تصدیق",
  "reg.sec.verifyHint": "آپ کی شناخت ہر رکن کو محفوظ رکھتی ہے۔",
  "reg.l.fullName": "پورا نام",
  "reg.l.dob": "تاریخ پیدائش",
  "reg.l.height": "قد",
  "reg.l.gender": "جنس",
  "reg.l.country": "ملک",
  "reg.l.city": "شہر",
  "reg.l.nationality": "قومیت",
  "reg.l.education": "تعلیم",
  "reg.l.profession": "پیشہ",
  "reg.l.income": "ماہانہ آمدنی",
  "reg.l.prayer": "نماز کی سطح",
  "reg.l.quran": "قرآن پڑھنا",
  "reg.l.knowledge": "دینی علم",
  "reg.l.beard": "داڑھی",
  "reg.l.hijab": "حجاب",
  "reg.l.dress": "اسلامی لباس",
  "reg.l.environment": "دینی ماحول",
  "reg.l.goals": "دینی اہداف",
  "reg.l.forGroom": "دولہا کے لیے",
  "reg.l.forBride": "دلہن کے لیے",
  "reg.l.fatherAlive": "والد حیات",
  "reg.l.motherAlive": "والدہ حیات",
  "reg.l.familyType": "خاندانی نظام",
  "reg.l.brothers": "بھائی",
  "reg.l.sisters": "بہنیں",
  "reg.l.waliName": "ولی کا نام",
  "reg.l.rel": "رشتہ",
  "reg.l.phone": "فون",
  "reg.l.whatsapp": "واٹس ایپ",
  "reg.l.email": "ای میل",
  "reg.l.cnic": "شناختی کارڈ نمبر",
  "reg.l.memberName": "رکن کا پورا نام",
  "reg.l.memberId": "رکن کا میثاق ID یا فون",
  "reg.ph.name": "مثلاً احمد رضا",
  "reg.ph.dob": "دن / مہینہ / سال",
  "reg.ph.height": "5' 10\"",
  "reg.ph.country": "پاکستان",
  "reg.ph.city": "لاہور",
  "reg.ph.zero": "0",
  "reg.ph.phone": "+92 300 0000000",
  "reg.ph.emailWali": "wali@example.com",
  "reg.ph.cnic": "XXXXX-XXXXXXX-X",
  "reg.upload.cnicFront": "شناختی کارڈ (سامنے)",
  "reg.upload.cnicBack": "شناختی کارڈ (پیچھے)",
  "reg.upload.selfie": "سیلفی",
  "reg.upload.tap": "اپلوڈ کے لیے دبائیں",
  "reg.dowry.needGender": "براہ کرم پہلے 'ذاتی' مرحلے پر اپنی جنس منتخب کریں۔",
  "reg.o.male": "مرد",
  "reg.o.female": "عورت",
  "reg.o.nat.pk": "پاکستانی",
  "reg.o.nat.in": "بھارتی",
  "reg.o.nat.uk": "برطانوی",
  "reg.o.nat.us": "امریکی",
  "reg.o.nat.ae": "اماراتی",
  "reg.o.nat.other": "دیگر",
  "reg.o.ed.matric": "میٹرک",
  "reg.o.ed.inter": "انٹرمیڈیٹ",
  "reg.o.ed.diploma": "ڈپلومہ",
  "reg.o.ed.bach": "بیچلر",
  "reg.o.ed.mast": "ماسٹرز",
  "reg.o.ed.mphil": "ایم فل",
  "reg.o.ed.phd": "پی ایچ ڈی",
  "reg.o.pr.student": "طالبعلم",
  "reg.o.pr.teacher": "استاد",
  "reg.o.pr.doctor": "ڈاکٹر",
  "reg.o.pr.engineer": "انجینئر",
  "reg.o.pr.business": "کاروبار",
  "reg.o.pr.govt": "سرکاری",
  "reg.o.pr.private": "پرائیویٹ",
  "reg.o.pr.freelance": "فری لانس",
  "reg.o.inc.a": "50k سے کم",
  "reg.o.inc.b": "50k – 100k",
  "reg.o.inc.c": "100k – 250k",
  "reg.o.inc.d": "250k – 500k",
  "reg.o.inc.e": "500k+",
  "reg.o.pray.never": "کبھی نہیں",
  "reg.o.pray.some": "کبھی کبھی",
  "reg.o.pray.friday": "صرف جمعہ",
  "reg.o.pray.daily": "روزانہ",
  "reg.o.pray.five": "پانچ وقت",
  "reg.o.pray.fiveM": "پانچ وقت مسجد میں",
  "reg.o.q.no": "نہیں پڑھ سکتے",
  "reg.o.q.learn": "سیکھ رہے ہیں",
  "reg.o.q.some": "کبھی کبھی",
  "reg.o.q.daily": "روزانہ",
  "reg.o.q.hafiz": "حافظ",
  "reg.o.k.beg": "ابتدائی",
  "reg.o.k.int": "درمیانی",
  "reg.o.k.good": "اچھا",
  "reg.o.k.adv": "اعلیٰ",
  "reg.o.k.scholar": "عالم",
  "reg.o.b.no": "نہیں",
  "reg.o.b.short": "چھوٹی داڑھی",
  "reg.o.b.sunnah": "سنت داڑھی",
  "reg.o.h.no": "نہیں",
  "reg.o.h.some": "کبھی کبھی",
  "reg.o.h.reg": "باقاعدہ",
  "reg.o.h.niqab": "نقاب",
  "reg.o.dr.modern": "جدید",
  "reg.o.dr.modest": "شریفانہ",
  "reg.o.dr.trad": "روایتی",
  "reg.o.dr.sunnah": "سنت",
  "reg.o.env.normal": "عام",
  "reg.o.env.rel": "دینی",
  "reg.o.env.high": "انتہائی دینی",
  "reg.o.g.hajj": "حج",
  "reg.o.g.umrah": "عمرہ",
  "reg.o.g.hifz": "قرآن حفظ",
  "reg.o.g.ed": "دینی تعلیم",
  "reg.o.g.family": "دینی خاندان",
  "reg.o.dw.mAccept": "میں جہیز قبول کروں گا",
  "reg.o.dw.mNo": "میں جہیز قبول نہیں کروں گا",
  "reg.o.dw.mDont": "کوئی فرق نہیں",
  "reg.o.dw.fGive": "ہم جہیز دیں گے",
  "reg.o.dw.fNo": "ہم جہیز نہیں دیں گے",
  "reg.o.dw.fPref": "جواب دینا پسند نہیں",
  "reg.o.ft.joint": "مشترکہ خاندان",
  "reg.o.ft.sep": "الگ خاندان",
  "reg.o.rel.father": "والد",
  "reg.o.rel.mother": "والدہ",
  "reg.o.rel.brother": "بھائی",
  "reg.o.rel.sister": "بہن",
  "reg.o.rel.uncle": "چچا",
  "reg.o.rel.aunt": "خالہ",
  "reg.o.rel.guardian": "سرپرست",
  "home.greeting": "السلام علیکم",
  "home.newMatches": "نئے میچز",
  "home.proposals": "پیغام",
  "home.chats": "چیٹس",
  "home.featured": "منتخب میچز",
  "home.recent": "حالیہ پیغام",
  "home.proposalReceived": "پیغام موصول",
  "discover.title": "تلاش",
  "discover.count": "تصدیق شدہ پروفائلز آپ کے فلٹرز سے میل کھاتے ہیں",
  "discover.filter.all": "سب",
  "matches.title": "میچز اور پیغام",
  "matches.received": "موصول",
  "matches.sent": "بھیجی گئی",
  "matches.accepted": "قبول",
  "matches.view": "دیکھیں",
  "matches.accept": "قبول",
  "matches.decline": "رد",
  "matches.openChat": "چیٹ کھولیں",
  "matches.empty": "اس حصے میں ابھی کوئی پیغام نہیں۔",
  "chats.title": "چیٹس",
  "chats.waliNotice": "آپ کا ولی ہر بات چیت دیکھ سکتا ہے۔",
  "chats.empty": "ابھی کوئی گفتگو نہیں۔ پیغام بھیج کر آغاز کریں۔",
  "chats.voice": "آواز",
  "chats.messagePlaceholder": "ادب سے پیغام لکھیں…",
  "chats.online": "آن لائن • ولی نگرانی میں",
  "chats.consent": "یہ گفتگو آپ کے ولی کو نظر آ رہی ہے۔ ادب سے بات کریں۔",
  "chats.startOfDay": "آج",
  "profile.about": "تعارف",
  "profile.eduProf": "تعلیم اور پیشہ",
  "profile.religion": "دینی معلومات",
  "profile.family": "خاندان",
  "profile.wali": "ولی کی معلومات",
  "profile.dowry": "جہیز کی ترجیح",
  "profile.compat": "ملتی جلتی پروفائلز",
  "profile.education": "تعلیم",
  "profile.profession": "پیشہ",
  "profile.height": "قد",
  "profile.sect": "مسلک",
  "profile.prayer": "نماز",
  "profile.quran": "قرآن",
  "profile.hijab": "حجاب",
  "profile.beard": "داڑھی",
  "profile.father": "والد",
  "profile.mother": "والدہ",
  "profile.siblings": "بہن بھائی",
  "profile.familyType": "خاندانی نظام",
  "profile.waliName": "ولی",
  "profile.verified": "تصدیق شدہ",
  "profile.sendProposal": "پیغام بھیجیں",
  "profile.save": "محفوظ",
  "profile.myTitle": "آپ کی پروفائل",
  "profile.mashAllah": "ما شاء اللہ",
  "profile.views": "پروفائل ویوز",
  "profile.complete": "مکمل",
  "profile.upgrade": "پلاٹینم پر اپگریڈ",
  "profile.upgradeDesc": "لامحدود پیغام · ترجیحی مرئیت",
  "profile.edit": "پروفائل ترمیم",
  "profile.editDesc": "ذاتی، دینی، خاندانی، جہیز",
  "profile.viewed": "مجھے کس نے دیکھا",
  "profile.viewedDesc": "اس ہفتے 42 اراکین",
  "profile.myWali": "میرا ولی",
  "profile.myWaliDesc": "عبداللہ رحمان · والد · تصدیق شدہ",
  "profile.strength": "پروفائل مضبوطی",
  "profile.strengthPersonal": "ذاتی معلومات",
  "profile.strengthReligious": "دینی معلومات",
  "profile.strengthFamily": "خاندانی تفصیلات",
  "profile.strengthPhotos": "تصاویر",
  "notif.title": "اطلاعات",
  "notif.markAllRead": "سب پڑھی نشان زد کریں",
  "notif.empty": "آپ اپ ٹو ڈیٹ ہیں۔",
  "premium.eyebrow": "میثاق پریمیم",
  "premium.title": "بامقصد تلاش میں سرمایہ کاری کریں۔",
  "premium.subtitle":
    "پریمیم اراکین کو 4 گنا زیادہ مخلص پیغام موصول ہوتے ہیں — پہلے سلام سے خاندان شامل۔",
  "premium.mostChosen": "سب سے مقبول",
  "premium.choose": "منتخب کریں",
  "premium.footer": "تمام پلانز حلال ہیں۔ کسی بھی وقت منسوخ کریں۔",
  "settings.title": "سیٹنگز",
  "settings.theme": "تھیم",
  "settings.language": "زبان",
  "settings.account": "اکاؤنٹ",
  "settings.preferences": "ترجیحات",
  "settings.support": "معاونت",
  "settings.logout": "لاگ آؤٹ",
  "settings.myAccount": "میرا اکاؤنٹ",
  "settings.privacy": "پرائیویسی",
  "settings.security": "سیکیورٹی و 2FA",
  "settings.notifications": "اطلاعات",
  "settings.premium": "میثاق پریمیم",
  "settings.help": "مدد گاہ",
  "settings.about": "میثاق کے بارے میں",
  "settings.terms": "شرائط",
  "settings.policy": "پرائیویسی پالیسی",
  "call.voice": "آواز کال",
  "call.video": "ویڈیو کال",
  "call.calling": "کال ہو رہی ہے…",
  "call.connecting": "محفوظ کنکشن جاری",
  "call.mute": "خاموش",
  "call.end": "ختم",
  "call.speaker": "اسپیکر",
  "call.camera": "کیمرا",
  "call.flip": "پلٹیں",
  "wali.dashboard": "ولی ڈیش بورڈ",
  "wali.name": "عبداللہ رحمان",
  "wali.guardianOf": "آپ سرپرست ہیں",
  "wali.stats.proposals": "پیغام",
  "wali.stats.chats": "چیٹس",
  "wali.stats.flags": "شکایات",
  "wali.current": "موجودہ پیغام",
  "wali.viewAll": "سب دیکھیں",
  "wali.inProgress": "جاری گفتگو",
  "wali.monitor": "نگرانی",
  "wali.fullVis": "آپ کو مکمل رسائی حاصل ہے۔",
  "wali.fullVisDesc": "آپ کے زیرِ نگرانی رکن کی ہر پیغام، آواز اور کال آپ دیکھ سکتے ہیں۔",
  "wali.proposals.title": "پیغام",
  "wali.proposals.for": "برائے",
  "wali.reviewProfile": "پروفائل جائزہ",
  "wali.waliChat": "ولی سے ولی چیٹ",
  "wali.chats.title": "چیٹ نگرانی",
  "wali.chats.for": "گفتگو",
  "wali.chats.viewChat": "چیٹ دیکھیں",
  "wali.chats.viewProfile": "پروفائل دیکھیں",
  "wali.chats.block": "بلاک",
  "wali.chats.delete": "حذف",
  "wali.chats.report": "رپورٹ",
  "wali.thread.readOnly": "صرف نگرانی",
  "wali.thread.notice": "آپ یہ گفتگو بحیثیت ولی دیکھ رہے ہیں۔ اراکین اس سے آگاہ ہیں۔",
  "wali.review.subtitle":
    "آپ یہ پروفائل بحیثیت ولی دیکھ رہے ہیں۔ ان کے ولی سے براہِ راست رابطہ کریں۔",
  "wali.review.theirWali": "ان کا ولی",
  "wali.review.waliName": "اسماعیل رحمان (والد)",
  "wali.review.waliContact": "+92 300 ••• ••• · CNIC سے تصدیق شدہ",
  "wali.review.message": "ولی کو براہِ راست پیغام",
  "wali.review.religious": "دینی",
  "wali.settings.title": "ولی سیٹنگز",
  "wali.set.profile": "پروفائل و تصدیق",
  "wali.set.privacy": "زیرِ نگرانی پرائیویسی",
  "wali.set.notif": "اطلاعات",
  "wali.set.lang": "زبان",
  "wali.set.theme": "تھیم",
  "admin.header": "میثاق ایڈمن",
  "admin.restricted": "محدود کنسول",
  "admin.super": "سپر",
  "admin.nav.dashboard": "ڈیش بورڈ",
  "admin.nav.members": "اراکین",
  "admin.nav.walis": "ولی",
  "admin.nav.verify": "تصدیق",
  "admin.nav.reports": "رپورٹس",
  "admin.nav.chats": "چیٹس",
  "admin.nav.calls": "کالز",
  "admin.nav.payments": "ادائیگیاں",
  "admin.nav.plans": "پلانز",
  "admin.nav.analytics": "تجزیات",
  "admin.nav.admins": "منتظمین",
  "admin.nav.cms": "سی ایم ایس",
  "admin.nav.settings": "سیٹنگز",
  "admin.kpi.members": "کل اراکین",
  "admin.kpi.walis": "فعال ولی",
  "admin.kpi.chats": "لائیو چیٹس",
  "admin.kpi.mrr": "MRR",
  "admin.kpi.thisWeek": "اس ہفتے",
  "admin.kpi.flagged": "نشان زد",
  "admin.nikahs": "منعقدہ نکاح",
  "admin.mom": "ماہ بہ ماہ",
  "admin.attention": "توجہ درکار",
  "admin.att.verif": "زیرِ التوا تصدیق",
  "admin.att.chats": "نشان زد چیٹس",
  "admin.att.reports": "صارف رپورٹس",
  "admin.att.disputes": "ادائیگی تنازعات",
  "admin.signups": "حالیہ رجسٹریشن",
  "admin.members.search": "اراکین تلاش کریں…",
  "admin.members.f.all": "سب",
  "admin.members.f.verified": "تصدیق شدہ",
  "admin.members.f.pending": "زیر التوا",
  "admin.members.f.premium": "پریمیم",
  "admin.members.f.reported": "رپورٹ شدہ",
  "admin.members.f.suspended": "معطل",
  "admin.walis.title": "ولی",
  "admin.walis.of": "کے ولی",
  "admin.verify.pending": "زیرِ التوا تصدیقات",
  "admin.verify.submitted": "2 گھنٹے پہلے جمع · CNIC · سیلفی",
  "admin.reports.reasons.msg": "نامناسب پیغام",
  "admin.reports.reasons.fake": "جعلی پروفائل",
  "admin.reports.reasons.harass": "ہراسانی",
  "admin.reports.reasons.spam": "اسپام / مارکیٹنگ",
  "admin.reports.by": "بذریعہ",
  "admin.reports.against": "خلاف",
  "admin.chats.summary": "فعال گفتگو",
  "admin.chats.flagged": "نشان زد",
  "admin.chats.msgs": "پیغامات",
  "admin.chats.last": "آخری",
  "admin.calls.waliPresent": "ولی موجود",
  "admin.calls.noWali": "ولی نہیں",
  "admin.pay.today": "آج",
  "admin.pay.month": "اس مہینے",
  "admin.pay.refunds": "ریفنڈ",
  "admin.pay.status.success": "کامیاب",
  "admin.pay.status.refund": "ریفنڈ",
  "admin.pay.status.failed": "ناکام",
  "admin.plans.subs": "سبسکرائبر",
  "admin.plans.month": "ماہ",
  "admin.analytics.dau": "روزانہ فعال",
  "admin.analytics.retention": "برقراری D30",
  "admin.analytics.avg": "اوسط پیغام / صارف",
  "admin.analytics.mtn": "میچ تا نکاح",
  "admin.analytics.byCountry": "ملک کے حساب سے اراکین",
  "admin.cms.terms": "شرائط",
  "admin.cms.privacy": "پرائیویسی پالیسی",
  "admin.cms.community": "کمیونٹی ہدایات",
  "admin.cms.qa": "اسلامی سوال جواب",
  "admin.cms.help": "مدد گاہ",
  "admin.cms.banners": "ہوم بینرز",
  "admin.cms.updated": "اپ ڈیٹ",
  "admin.cms.articles": "مضامین",
  "admin.cms.active": "فعال",
  "admin.admins.invite": "منتظم مدعو کریں",
  "admin.admins.roles.super": "سپر ایڈمن",
  "admin.admins.roles.mod": "ماڈریٹر",
  "admin.admins.roles.support": "سپورٹ",
  "admin.set.platform": "پلیٹ فارم",
  "admin.set.security": "سیکیورٹی",
  "admin.set.compliance": "تعمیل",
  "admin.set.p.branding": "برانڈنگ و لوگو",
  "admin.set.p.onboarding": "آن بورڈنگ",
  "admin.set.p.algo": "مطابقت الگورتھم",
  "admin.set.p.langs": "زبانوں کے پیکج",
  "admin.set.s.pw": "پاس ورڈ پالیسی",
  "admin.set.s.2fa": "منتظمین کے لیے 2FA",
  "admin.set.s.sess": "سیشن حدود",
  "admin.set.s.audit": "آڈٹ لاگ",
  "admin.set.c.retention": "ڈیٹا برقراری",
  "admin.set.c.forgotten": "فراموش کیے جانے کا حق",
  "admin.set.c.export": "ڈیٹا برآمد",
  "admin.set.c.laws": "علاقائی قوانین",
  "admin.login.title": "منتظم",
  "admin.login.subtitle": "محدود رسائی",
  "admin.login.notice": "منتظم اکاؤنٹس پہلے سے بنائے گئے ہیں۔ کوئی عوامی رجسٹریشن نہیں۔",
  "admin.login.email": "منتظم ای میل",
  "admin.login.emailPh": "admin@misaq.app",
  "admin.login.pw": "پاس ورڈ",
  "admin.login.pwPh": "••••••••",
  "admin.login.otp": "دو مرحلوں کا کوڈ",
  "admin.login.otpPh": "6 ہندسوں کا کوڈ",
  "admin.login.enter": "ایڈمن کنسول میں داخل ہوں",
  "admin.login.back": "رکن لاگ ان پر واپس",
  "state.empty": "ابھی کچھ نہیں۔",
  "state.error.title": "کچھ غلط ہو گیا",
  "state.error.desc": "براہ کرم تھوڑی دیر میں دوبارہ کوشش کریں۔",
};

const ru: Dict = {
  "nav.home": "Home",
  "nav.discover": "Talash",
  "nav.matches": "Rishtay",
  "nav.chats": "Baat cheet",
  "nav.profile": "Profile",
  "common.back": "Wapas",
  "common.continue": "Jari rakhein",
  "common.cancel": "Mansookh",
  "common.confirm": "Tasdeeq",
  "common.save": "Mehfooz karein",
  "common.search": "Talash",
  "common.filter": "Filters",
  "common.viewAll": "Sab dekhein",
  "common.retry": "Dobara koshish",
  "common.loading": "Load ho raha hai…",
  "common.empty": "Abhi kuch nahin",
  "common.error": "Kuch ghalat ho gaya",
  "common.online": "Online",
  "common.typing": "likh rahe hain…",
  "common.today": "Aaj",
  "common.yesterday": "Kal",
  "common.earlier": "Pehle",
  "common.unread": "Ghair parhi",
  "common.read": "Parhi gayi",
  "common.yrs": "saal",
  "common.edit": "Edit",
  "common.view": "Dekhein",
  "common.approve": "Manzoor",
  "common.reject": "Mustard",
  "common.decline": "Rad",
  "common.investigate": "Tahqeeq",
  "common.suspend": "Muattal",
  "common.dismiss": "Barkhast",
  "common.pending": "Zer-e-iltawa",
  "common.verified": "Tasdeeq shudah",
  "common.step": "Step",
  "common.of": "of",
  "common.optional": "Ikhtiyari",
  "common.required": "Lazmi",
  "common.yes": "Haan",
  "common.no": "Nahin",
  "common.other": "Dosra",
  "splash.tagline":
    '"Aur us ki nishaniyon mein se yeh hai ke us ne tumhare liye tumhari jins se jorey banaye…" — Ar-Rum 30:21',
  "splash.skip": "Chhorein",
  "welcome.title": "Ek mulaqat jo duniya se pehle likhi ja chuki.",
  "welcome.subtitle":
    "Misaq ek ehd hai — nikah ka platform jo Islami qadar, waqar aur khandani shamooliat par qaim hai.",
  "welcome.create": "Account banayein",
  "welcome.have": "Mera pehle se account hai",
  "welcome.pillar1.t": "Tasdeeq shudah profiles",
  "welcome.pillar1.d": "Har member CNIC aur Wali interview se tasdeeq shudah.",
  "welcome.pillar2.t": "Khandan markaz mein",
  "welcome.pillar2.d": "Aap ka Wali har guftagu dekhta hai. Kuch chhupa nahin.",
  "welcome.pillar3.t": "Nikah, dating nahin",
  "welcome.pillar3.d": "Munazzam paighaam — na swipe, na ibhaam.",
  "theme.step": "Step 1 of 2",
  "theme.title": "Apni fiza chunein",
  "theme.hint":
    "Woh rang chunein jo aap ke dil ko sukoon de. Aap Settings se kabhi bhi badal sakte hain.",
  "theme.light": "Roshan",
  "theme.dark": "Gehri",
  "theme.lightDesc": "Cream aur maroon. Roshan aur khula.",
  "theme.darkDesc": "Kaale par gehra maroon. Pur-sukoon aur khamosh.",
  "lang.step": "Step 2 of 2",
  "lang.title": "Apni zubaan chunein",
  "lang.hint": "Aap kisi bhi waqt Settings se badal sakte hain.",
  "lang.continue": "Jari rakhein",
  "auth.login.title": "Khush aamdeed",
  "auth.login.subtitle": "Barakat ke saath apni talash jari rakhne ke liye sign in karein.",
  "auth.login.email": "Email ya phone",
  "auth.login.emailPh": "you@example.com",
  "auth.login.password": "Password",
  "auth.login.passwordPh": "••••••••",
  "auth.login.remember": "Mujhe yaad rakhein",
  "auth.login.forgot": "Bhool gaye?",
  "auth.login.signin": "Sign in",
  "auth.login.or": "ya",
  "auth.login.wali": "Wali / Guardian ke tor par sign in",
  "auth.login.new": "Naye hain?",
  "auth.login.create": "Account banayein",
  "auth.login.admin": "Administrator login",
  "auth.login.error": "Ghalat email ya password.",
  "auth.reg.title": "Account banayein",
  "auth.reg.hint": "Kaun register ho raha hai?",
  "auth.reg.member.t": "Dulhan ya Dulha",
  "auth.reg.member.d":
    "Profile banayein, paighaam mausool karein, aur Wali ke zariye khandan ko shamil karein.",
  "auth.reg.wali.t": "Wali / Guardian",
  "auth.reg.wali.d":
    "Kisi member ki nigraani ke liye register hon — paighaam dekhein, chat nigraani karein.",
  "auth.reg.adminNote":
    "Administrators pehle se banaye gaye hain. Public admin registration dastyab nahin.",
  "auth.reg.already": "Pehle se registered hain?",
  "auth.reg.signin": "Sign in",
  "reg.back": "Wapas",
  "reg.continue": "Jari rakhein",
  "reg.finish": "Mukammal karein aur Misaq mein dakhil hon",
  "reg.step": "Step",
  "reg.of": "of",
  "reg.title.member": "Member Registration",
  "reg.title.wali": "Wali Registration",
  "reg.s.personal": "Zaati",
  "reg.s.education": "Taleem",
  "reg.s.religious": "Deeni",
  "reg.s.dowry": "Jahez",
  "reg.s.family": "Khandan",
  "reg.s.wali": "Wali",
  "reg.s.aboutYou": "Aap ke baare mein",
  "reg.s.relationship": "Rishta",
  "reg.s.verification": "Tasdeeq",
  "reg.sec.personal": "Zaati maloomat",
  "reg.sec.personalHint": "Sirf match ho chuke khandanon ko dikhaya jata hai.",
  "reg.sec.eduProf": "Taleem aur pesha",
  "reg.sec.religious": "Deeni maloomat",
  "reg.sec.religiousHint": "Pehle se di gayi options — sahi match dhoondhne mein madad.",
  "reg.sec.dowry": "Jahez ki tarjeeh",
  "reg.sec.dowryHint": "Imaandari se jawab — shafafiyat mein barakat.",
  "reg.sec.family": "Khandani maloomat",
  "reg.sec.waliInfo": "Wali ki maloomat",
  "reg.sec.waliInfoHint": "Har member ko ek Wali link karna lazmi hai.",
  "reg.sec.aboutYou": "Aap ke baare mein",
  "reg.sec.linkedMember": "Linked member",
  "reg.sec.linkedMemberHint": "Jis dulhan/dulha ki aap nigraani karenge us ki tafseelat.",
  "reg.sec.verify": "Tasdeeq",
  "reg.sec.verifyHint": "Aap ki shanakht har member ko mehfooz rakhti hai.",
  "reg.l.fullName": "Poora naam",
  "reg.l.dob": "Tareekh-e-paidaish",
  "reg.l.height": "Qad",
  "reg.l.gender": "Jins",
  "reg.l.country": "Mulk",
  "reg.l.city": "Shehar",
  "reg.l.nationality": "Qaumiat",
  "reg.l.education": "Taleem",
  "reg.l.profession": "Pesha",
  "reg.l.income": "Mahana aamdani",
  "reg.l.prayer": "Namaz ka darja",
  "reg.l.quran": "Quran parhna",
  "reg.l.knowledge": "Deeni ilm",
  "reg.l.beard": "Daarhi",
  "reg.l.hijab": "Hijab",
  "reg.l.dress": "Islami libaas",
  "reg.l.environment": "Deeni maahol",
  "reg.l.goals": "Deeni ahdaaf",
  "reg.l.forGroom": "Dulha ke liye",
  "reg.l.forBride": "Dulhan ke liye",
  "reg.l.fatherAlive": "Walid hayat",
  "reg.l.motherAlive": "Walida hayat",
  "reg.l.familyType": "Khandani nizaam",
  "reg.l.brothers": "Bhai",
  "reg.l.sisters": "Behnain",
  "reg.l.waliName": "Wali ka naam",
  "reg.l.rel": "Rishta",
  "reg.l.phone": "Phone",
  "reg.l.whatsapp": "WhatsApp",
  "reg.l.email": "Email",
  "reg.l.cnic": "CNIC number",
  "reg.l.memberName": "Member ka poora naam",
  "reg.l.memberId": "Member ka Misaq ID ya phone",
  "reg.ph.name": "mislan Ahmed Raza",
  "reg.ph.dob": "DD / MM / YYYY",
  "reg.ph.height": "5' 10\"",
  "reg.ph.country": "Pakistan",
  "reg.ph.city": "Lahore",
  "reg.ph.zero": "0",
  "reg.ph.phone": "+92 300 0000000",
  "reg.ph.emailWali": "wali@example.com",
  "reg.ph.cnic": "XXXXX-XXXXXXX-X",
  "reg.upload.cnicFront": "CNIC saamne",
  "reg.upload.cnicBack": "CNIC peechhe",
  "reg.upload.selfie": "Selfie",
  "reg.upload.tap": "Upload karne ke liye dabayein",
  "reg.dowry.needGender": "Barah-e-karam pehle Zaati step par apni jins muntakhib karein.",
  "reg.o.male": "Mard",
  "reg.o.female": "Aurat",
  "reg.o.nat.pk": "Pakistani",
  "reg.o.nat.in": "Indian",
  "reg.o.nat.uk": "British",
  "reg.o.nat.us": "American",
  "reg.o.nat.ae": "Emirati",
  "reg.o.nat.other": "Dosra",
  "reg.o.ed.matric": "Matric",
  "reg.o.ed.inter": "Intermediate",
  "reg.o.ed.diploma": "Diploma",
  "reg.o.ed.bach": "Bachelor's",
  "reg.o.ed.mast": "Master's",
  "reg.o.ed.mphil": "MPhil",
  "reg.o.ed.phd": "PhD",
  "reg.o.pr.student": "Taalib-e-ilm",
  "reg.o.pr.teacher": "Ustad",
  "reg.o.pr.doctor": "Doctor",
  "reg.o.pr.engineer": "Engineer",
  "reg.o.pr.business": "Karobaar",
  "reg.o.pr.govt": "Sarkari",
  "reg.o.pr.private": "Private",
  "reg.o.pr.freelance": "Freelancer",
  "reg.o.inc.a": "50k se kam",
  "reg.o.inc.b": "50k – 100k",
  "reg.o.inc.c": "100k – 250k",
  "reg.o.inc.d": "250k – 500k",
  "reg.o.inc.e": "500k+",
  "reg.o.pray.never": "Kabhi nahin",
  "reg.o.pray.some": "Kabhi kabhi",
  "reg.o.pray.friday": "Sirf Jumma",
  "reg.o.pray.daily": "Rozana",
  "reg.o.pray.five": "Paanch waqt",
  "reg.o.pray.fiveM": "Paanch waqt masjid mein",
  "reg.o.q.no": "Nahin parh sakte",
  "reg.o.q.learn": "Seekh rahe hain",
  "reg.o.q.some": "Kabhi kabhi",
  "reg.o.q.daily": "Rozana",
  "reg.o.q.hafiz": "Hafiz",
  "reg.o.k.beg": "Ibtidai",
  "reg.o.k.int": "Darmiyani",
  "reg.o.k.good": "Achha",
  "reg.o.k.adv": "Ala",
  "reg.o.k.scholar": "Aalim",
  "reg.o.b.no": "Nahin",
  "reg.o.b.short": "Chhoti daarhi",
  "reg.o.b.sunnah": "Sunnah daarhi",
  "reg.o.h.no": "Nahin",
  "reg.o.h.some": "Kabhi kabhi",
  "reg.o.h.reg": "Baaqaida",
  "reg.o.h.niqab": "Niqab",
  "reg.o.dr.modern": "Jadeed",
  "reg.o.dr.modest": "Sharifana",
  "reg.o.dr.trad": "Riwayati",
  "reg.o.dr.sunnah": "Sunnah",
  "reg.o.env.normal": "Aam",
  "reg.o.env.rel": "Deeni",
  "reg.o.env.high": "Intehai deeni",
  "reg.o.g.hajj": "Hajj",
  "reg.o.g.umrah": "Umrah",
  "reg.o.g.hifz": "Quran hifz",
  "reg.o.g.ed": "Deeni taleem",
  "reg.o.g.family": "Deeni khandan",
  "reg.o.dw.mAccept": "Main jahez qabool karunga",
  "reg.o.dw.mNo": "Main jahez qabool nahin karunga",
  "reg.o.dw.mDont": "Koi farq nahin",
  "reg.o.dw.fGive": "Hum jahez denge",
  "reg.o.dw.fNo": "Hum jahez nahin denge",
  "reg.o.dw.fPref": "Jawab dena pasand nahin",
  "reg.o.ft.joint": "Mushtarka khandan",
  "reg.o.ft.sep": "Alag khandan",
  "reg.o.rel.father": "Walid",
  "reg.o.rel.mother": "Walida",
  "reg.o.rel.brother": "Bhai",
  "reg.o.rel.sister": "Behen",
  "reg.o.rel.uncle": "Chacha",
  "reg.o.rel.aunt": "Khala",
  "reg.o.rel.guardian": "Sarparast",
  "home.greeting": "Assalamu alaikum",
  "home.newMatches": "Naye rishtay",
  "home.proposals": "Paighaam",
  "home.chats": "Baat cheet",
  "home.featured": "Muntakhib rishtay",
  "home.recent": "Haaliya paighaam",
  "home.proposalReceived": "Paighaam mausool",
  "discover.title": "Talash",
  "discover.count": "tasdeeq shudah profiles aap ke filters se milte hain",
  "discover.filter.all": "Sab",
  "matches.title": "Rishtay aur paighaam",
  "matches.received": "Mausool",
  "matches.sent": "Bheji gayi",
  "matches.accepted": "Qabool",
  "matches.view": "Dekhein",
  "matches.accept": "Qabool",
  "matches.decline": "Rad",
  "matches.openChat": "Chat kholein",
  "matches.empty": "Is hisse mein abhi koi paighaam nahin.",
  "chats.title": "Baat cheet",
  "chats.waliNotice": "Aap ka Wali har guftagu dekh sakta hai.",
  "chats.empty": "Abhi koi guftagu nahin. Paighaam bhej kar aghaz karein.",
  "chats.voice": "Awaaz",
  "chats.messagePlaceholder": "Adab se paighaam likhein…",
  "chats.online": "Online • Wali nigraani mein",
  "chats.consent": "Yeh guftagu aap ke Wali ko nazar aa rahi hai. Adab se baat karein.",
  "chats.startOfDay": "Aaj",
  "profile.about": "Taruf",
  "profile.eduProf": "Taleem aur pesha",
  "profile.religion": "Deeni maloomat",
  "profile.family": "Khandan",
  "profile.wali": "Wali ki maloomat",
  "profile.dowry": "Jahez ki tarjeeh",
  "profile.compat": "Milti julti profiles",
  "profile.education": "Taleem",
  "profile.profession": "Pesha",
  "profile.height": "Qad",
  "profile.sect": "Maslak",
  "profile.prayer": "Namaz",
  "profile.quran": "Quran",
  "profile.hijab": "Hijab",
  "profile.beard": "Daarhi",
  "profile.father": "Walid",
  "profile.mother": "Walida",
  "profile.siblings": "Behen bhai",
  "profile.familyType": "Khandani nizaam",
  "profile.waliName": "Wali",
  "profile.verified": "Tasdeeq shudah",
  "profile.sendProposal": "Paighaam bhejein",
  "profile.save": "Mehfooz",
  "profile.myTitle": "Aap ki profile",
  "profile.mashAllah": "Ma sha Allah",
  "profile.views": "Profile views",
  "profile.complete": "Mukammal",
  "profile.upgrade": "Platinum par upgrade",
  "profile.upgradeDesc": "La-mehdood paighaam · tarjeehi visibility",
  "profile.edit": "Profile edit",
  "profile.editDesc": "Zaati, deeni, khandani, jahez",
  "profile.viewed": "Mujhe kis ne dekha",
  "profile.viewedDesc": "Is hafte 42 members",
  "profile.myWali": "Mera Wali",
  "profile.myWaliDesc": "Abdullah Rahman · Walid · Tasdeeq shudah",
  "profile.strength": "Profile mazbooti",
  "profile.strengthPersonal": "Zaati maloomat",
  "profile.strengthReligious": "Deeni maloomat",
  "profile.strengthFamily": "Khandani tafseelat",
  "profile.strengthPhotos": "Tasaweer",
  "notif.title": "Ittilaat",
  "notif.markAllRead": "Sab parhi nishaan zad karein",
  "notif.empty": "Aap up to date hain.",
  "premium.eyebrow": "Misaq Premium",
  "premium.title": "Ba-maqsad talash mein sarmaya kaari karein.",
  "premium.subtitle":
    "Premium arkaan ko 4 gunah zyada mukhlis paighaam milte hain — pehle salaam se khandan shamil.",
  "premium.mostChosen": "Sab se maqbool",
  "premium.choose": "Muntakhib karein",
  "premium.footer": "Tamam plans halal hain. Kisi bhi waqt mansookh karein.",
  "settings.title": "Settings",
  "settings.theme": "Theme",
  "settings.language": "Zubaan",
  "settings.account": "Account",
  "settings.preferences": "Tarjeehat",
  "settings.support": "Madad",
  "settings.logout": "Log out",
  "settings.myAccount": "Mera account",
  "settings.privacy": "Privacy",
  "settings.security": "Security aur 2FA",
  "settings.notifications": "Ittilaat",
  "settings.premium": "Misaq Premium",
  "settings.help": "Madad centre",
  "settings.about": "Misaq ke bare mein",
  "settings.terms": "Sharait",
  "settings.policy": "Privacy policy",
  "call.voice": "Awaaz call",
  "call.video": "Video call",
  "call.calling": "Call ho rahi hai…",
  "call.connecting": "Mehfooz connection jaari",
  "call.mute": "Khamosh",
  "call.end": "Khatam",
  "call.speaker": "Speaker",
  "call.camera": "Camera",
  "call.flip": "Palten",
  "wali.dashboard": "Wali Dashboard",
  "wali.name": "Abdullah Rahman",
  "wali.guardianOf": "Aap sarparast hain",
  "wali.stats.proposals": "Paighaam",
  "wali.stats.chats": "Chats",
  "wali.stats.flags": "Shikayaat",
  "wali.current": "Maujooda paighaam",
  "wali.viewAll": "Sab dekhein",
  "wali.inProgress": "Jaari guftagu",
  "wali.monitor": "Nigraani",
  "wali.fullVis": "Aap ko mukammal rasai hai.",
  "wali.fullVisDesc":
    "Aap ke zer-e-nigraani member ki har paighaam, awaaz aur call aap dekh sakte hain.",
  "wali.proposals.title": "Paighaam",
  "wali.proposals.for": "Ke liye",
  "wali.reviewProfile": "Profile jaiza",
  "wali.waliChat": "Wali se Wali chat",
  "wali.chats.title": "Chat nigraani",
  "wali.chats.for": "guftagu",
  "wali.chats.viewChat": "Chat dekhein",
  "wali.chats.viewProfile": "Profile dekhein",
  "wali.chats.block": "Block",
  "wali.chats.delete": "Delete",
  "wali.chats.report": "Report",
  "wali.thread.readOnly": "Sirf nigraani",
  "wali.thread.notice": "Aap yeh guftagu bahesiyat-e-Wali dekh rahe hain. Members aagah hain.",
  "wali.review.subtitle":
    "Aap yeh profile bahesiyat-e-Wali dekh rahe hain. Un ke Wali se raabta karein.",
  "wali.review.theirWali": "Un ka Wali",
  "wali.review.waliName": "Ismail Rahman (Walid)",
  "wali.review.waliContact": "+92 300 ••• ••• · CNIC se tasdeeq shudah",
  "wali.review.message": "Wali ko seedha paighaam",
  "wali.review.religious": "Deeni",
  "wali.settings.title": "Wali settings",
  "wali.set.profile": "Profile aur tasdeeq",
  "wali.set.privacy": "Zer-e-nigraani privacy",
  "wali.set.notif": "Ittilaat",
  "wali.set.lang": "Zubaan",
  "wali.set.theme": "Theme",
  "admin.header": "Misaq Admin",
  "admin.restricted": "Mehdood console",
  "admin.super": "SUPER",
  "admin.nav.dashboard": "Dashboard",
  "admin.nav.members": "Arkaan",
  "admin.nav.walis": "Wali",
  "admin.nav.verify": "Tasdeeq",
  "admin.nav.reports": "Reports",
  "admin.nav.chats": "Chats",
  "admin.nav.calls": "Calls",
  "admin.nav.payments": "Adaigiyan",
  "admin.nav.plans": "Plans",
  "admin.nav.analytics": "Tajziyat",
  "admin.nav.admins": "Admins",
  "admin.nav.cms": "CMS",
  "admin.nav.settings": "Settings",
  "admin.kpi.members": "Kul arkaan",
  "admin.kpi.walis": "Faal Wali",
  "admin.kpi.chats": "Live chats",
  "admin.kpi.mrr": "MRR",
  "admin.kpi.thisWeek": "is hafte",
  "admin.kpi.flagged": "nishaan zad",
  "admin.nikahs": "Munaqid Nikah",
  "admin.mom": "Maah ba maah",
  "admin.attention": "Tawajjuh darkaar",
  "admin.att.verif": "Zer-e-iltawa tasdeeqaat",
  "admin.att.chats": "Nishaan zad chats",
  "admin.att.reports": "Sarif reports",
  "admin.att.disputes": "Adaigi tanaza'aat",
  "admin.signups": "Haaliya signups",
  "admin.members.search": "Arkaan talash karein…",
  "admin.members.f.all": "Sab",
  "admin.members.f.verified": "Tasdeeq shudah",
  "admin.members.f.pending": "Zer-e-iltawa",
  "admin.members.f.premium": "Premium",
  "admin.members.f.reported": "Reported",
  "admin.members.f.suspended": "Muattal",
  "admin.walis.title": "Wali",
  "admin.walis.of": "ke Wali",
  "admin.verify.pending": "zer-e-iltawa tasdeeqaat",
  "admin.verify.submitted": "2 ghante pehle jama · CNIC · Selfie",
  "admin.reports.reasons.msg": "Namunasib paighaam",
  "admin.reports.reasons.fake": "Jaali profile",
  "admin.reports.reasons.harass": "Harasgi",
  "admin.reports.reasons.spam": "Spam / marketing",
  "admin.reports.by": "Bazariya",
  "admin.reports.against": "Khilaf",
  "admin.chats.summary": "faal guftagu",
  "admin.chats.flagged": "nishaan zad",
  "admin.chats.msgs": "paighamaat",
  "admin.chats.last": "Aakhri",
  "admin.calls.waliPresent": "Wali maujood",
  "admin.calls.noWali": "Wali nahin",
  "admin.pay.today": "Aaj",
  "admin.pay.month": "Is mahine",
  "admin.pay.refunds": "Refunds",
  "admin.pay.status.success": "Kamyab",
  "admin.pay.status.refund": "Refund",
  "admin.pay.status.failed": "Nakaam",
  "admin.plans.subs": "subscribers",
  "admin.plans.month": "mahina",
  "admin.analytics.dau": "DAU",
  "admin.analytics.retention": "Retention D30",
  "admin.analytics.avg": "Aost paighaam / sarif",
  "admin.analytics.mtn": "Match tak Nikah",
  "admin.analytics.byCountry": "Arkaan mulk ke husaab se",
  "admin.cms.terms": "Sharait",
  "admin.cms.privacy": "Privacy policy",
  "admin.cms.community": "Community hidayat",
  "admin.cms.qa": "Islami sawal jawab",
  "admin.cms.help": "Madad centre",
  "admin.cms.banners": "Home banners",
  "admin.cms.updated": "Update",
  "admin.cms.articles": "mazamin",
  "admin.cms.active": "faal",
  "admin.admins.invite": "Admin da'wat karein",
  "admin.admins.roles.super": "Super Admin",
  "admin.admins.roles.mod": "Moderator",
  "admin.admins.roles.support": "Support",
  "admin.set.platform": "Platform",
  "admin.set.security": "Security",
  "admin.set.compliance": "Ta'meel",
  "admin.set.p.branding": "Branding aur logo",
  "admin.set.p.onboarding": "Onboarding",
  "admin.set.p.algo": "Compatibility algorithm",
  "admin.set.p.langs": "Zubaan packs",
  "admin.set.s.pw": "Password policy",
  "admin.set.s.2fa": "Admins ke liye 2FA",
  "admin.set.s.sess": "Session limits",
  "admin.set.s.audit": "Audit log",
  "admin.set.c.retention": "Data retention",
  "admin.set.c.forgotten": "Faramosh kiye jaane ka haq",
  "admin.set.c.export": "Data export",
  "admin.set.c.laws": "Ilaqai qawaneen",
  "admin.login.title": "Administrator",
  "admin.login.subtitle": "Mehdood rasai",
  "admin.login.notice": "Admin accounts pehle se banaye gaye. Koi public registration nahin.",
  "admin.login.email": "Admin email",
  "admin.login.emailPh": "admin@misaq.app",
  "admin.login.pw": "Password",
  "admin.login.pwPh": "••••••••",
  "admin.login.otp": "Do marhaley ka code",
  "admin.login.otpPh": "6 hindson ka code",
  "admin.login.enter": "Admin console mein dakhil hon",
  "admin.login.back": "Member login par wapas",
  "state.empty": "Abhi kuch nahin.",
  "state.error.title": "Kuch ghalat ho gaya",
  "state.error.desc": "Barah-e-karam thodi der mein dobara koshish karein.",
};

const translations: Record<Lang, Dict> = { en, ur, ru };

type Ctx = {
  theme: Theme;
  setTheme: (t: Theme) => void;
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const MisaqCtx = createContext<Ctx>({
  theme: "light",
  setTheme: () => {},
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export const useMisaq = () => useContext(MisaqCtx);
export const useT = () => useMisaq().t;

export function MisaqProviders({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>("light");
  const [lang, setLangState] = useState<Lang>("en");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const t =
      (typeof window !== "undefined" && (localStorage.getItem("misaq-theme") as Theme)) || "light";
    const l =
      (typeof window !== "undefined" && (localStorage.getItem("misaq-lang") as Lang)) || "en";
    setThemeState(t);
    setLangState(l);
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.classList.toggle("dark", theme === "dark");
  }, [theme]);

  useEffect(() => {
    if (typeof document === "undefined" || !hydrated) return;
    document.documentElement.lang = lang === "ur" ? "ur" : "en";
    document.documentElement.dir = lang === "ur" ? "rtl" : "ltr";
  }, [lang, hydrated]);

  const setTheme = (t: Theme) => {
    setThemeState(t);
    if (typeof window !== "undefined") localStorage.setItem("misaq-theme", t);
  };
  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem("misaq-lang", l);
  };

  const t = useMemo(() => {
    const dict = translations[lang] ?? translations.en;
    return (key: string) => dict[key] ?? translations.en[key] ?? key;
  }, [lang]);

  return (
    <MisaqCtx.Provider value={{ theme, setTheme, lang, setLang, t }}>{children}</MisaqCtx.Provider>
  );
}
